package org.apache.cocoon.processor.dcp;

import java.io.*;
import java.util.*;
import org.w3c.dom.*;
import javax.servlet.http.*;
import org.apache.cocoon.processor.*;
import org.apache.cocoon.framework.*;
import org.apache.cocoon.interpreter.*;

/**
 * This class implements a DOM processor that expands XML documents
 * replacing dynamic content generation processing instructions by the return
 * value of user-supplied logic.
 * 
 * @author <a href="mailto:rrocha@plenix.org">Ricardo Rocha</a>
 * @version $Revision: 1.1.1.1 $ $Date: 1999-11-09 01:51:14 $
*/

public class DCPProcessor extends AbstractActor implements Processor, Status {
    
    /**
     * This method scans a DOM tree replacing <I>&lt;?dcp?&gt;</I> processing instructions
     * by dynamic content generated by user-supplied programs. These programs are
     * dynamically loaded according to directives contained in <I>&lt;?dcp-object?&gt;</I>
     * processing instructions. 
     *
     * @param document The document to be processed for dynamic content
     * @param parameters The table of invocation environment variables to be used during processing 
     * @return The expanded document
     * @throws Exception When any error occurs during processing
     */
    public Document process(Document document, Dictionary parameters) throws Exception {
        InterpreterFactory factory = (InterpreterFactory) director.getActor("interpreters");
        (new DCPEngine(document, factory, parameters)).process();
        return document;
    }
    
    /**
     * This method is called by the cache system to evaluate the status
     * of this changeable point for the given context 
     * (normally an HTTP request). Since even if the scripts didn't change
     * we can't assume anything about it, this method is today
     * left unimplemented (it always returns "true") but should call 
     * similar hooks inside the DCP components if available.
     */
    public boolean hasChanged(Object context) {
        return true;
    }
    
    public String getStatus() {
        return "Dynamic Content Processor";
    }
    
}