/* ========================================================================= *
 *                   The Apache Software License, Version 1.1                *
 * ========================================================================= *
 *          Copyright (C) 1999-2003 The Apache Software Foundation.          *
 *                           All rights reserved.                            *
 *                                                                           *
 * Redistribution  and  use in  source and  binary  forms,  with or  without *
 * modification,  are permitted provided  that the following  conditions are *
 * met:                                                                      *
 *                                                                           *
 * 1. Redistributions of source code must retain the above copyright notice, *
 *    this list of conditions and the following disclaimer.                  *
 *                                                                           *
 * 2. Redistributions  in binary  form must  reproduce  the above  copyright *
 *    notice,  this list of  conditions and the following  disclaimer in the *
 *    documentation and/or other materials provided with the distribution.   *
 *                                                                           *
 * 3. The end-user  documentation included with the redistribution,  if any, *
 *    must include the following acknowledgment:                             *
 *                                                                           *
 *             "This product includes software developed by the              *
 *            Apache Software Foundation <http://www.apache.org/>."          *
 *                                                                           *
 *    Alternately, this acknowledgment may appear in the software itself, if *
 *    and wherever such third-party acknowledgments normally appear.         *
 *                                                                           *
 * 4. The names "Apache Cocoon" and "Apache Software Foundation" must not be *
 *    used to endorse or promote products derived from this software without *
 *    prior  written  permission.  For written  permission,  please  contact *
 *    <mailto:apache@apache.org>.                                            *
 *                                                                           *
 * 5. Products derived  from this software  may not be called "Apache",  nor *
 *    may "Apache" appear in their name, without prior written permission of *
 *    the Apache Software Foundation.                                        *
 *                                                                           *
 * ------------------------------------------------------------------------- *
 *                                                                           *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESSED OR IMPLIED WARRANTIES *
 * INCLUDING, BUT NOT LIMITED TO,  THE IMPLIED WARRANTIES OF MERCHANTABILITY *
 * AND FITNESS  FOR A PARTICULAR  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL *
 * THE  APACHE SOFTWARE  FOUNDATION  OR ITS CONTRIBUTORS BE  LIABLE FOR  ANY *
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGE *
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVI- *
 * CES;  LOSS OF USE, DATA,  OR PROFITS;  OR BUSINESS INTERRUPTION)  HOWEVER *
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABI- *
 * LITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY WAY OUT *
 * OF THE USE OF THIS SOFTWARE,  EVEN IF ADVISED OF THE  POSSIBILITY OF SUCH *
 * DAMAGE.                                                                   *
 *                                                                           *
 * This software consists of voluntary contributions made by many individua- *
 * ls on behalf of the Apache Software Foundation and was originally created *
 * by  Stefano Mazzocchi  <mailto:stefano@apache.org>.  For more information *
 * about the Apache Software Foundation please see <http://www.apache.org/>. *
 *                                                                           *
 * ------------------------------------------------------------------------- */


/**
 * <p>
 *   The top level object.
 * </p>
 *
 * <p>
 *   <dl>
 *     <dt><b>Authors:</b></dt>
 *     <dd>
 *       <a href="mailto:coliver AT apache.org">Christopher Oliver</a>.
 *     </dd>
 *     <dt><b>Copyright:</b></dt>
 *     <dd>
 *       Copyright &copy; 2002-2003
 *       <a href="http://www.apache.org/">The Apache Software Foundation</a>.
 *       All rights reserved.
 *     </dd>
 *   </dl>
 * </p>
 */
interface Global {

    /**
     * Reference to the logging facility.
     */
    readonly attribute Log log;

    /**
     * Prints a message on standard out followed by a newline.
     *
     * @param message message to be printed
     */

    void print(in string message);

    /**
     * Passes control to the Cocoon sitemap to generate the output page.
     *
     * @param uri the relative URL of the page to be sent back to the client.
     * @param bean a context object which can be accessed inside this page to
     *             extract various values and place them in the generated page.
     */
    void sendPage(in string uri, in Object bean);

    /**
     * Passes control to the Cocoon sitemap to generate the output page.
     *
     * <p>The flow script is suspended after the page is generated and the whole execution stack saved in a Continuation object </p>
     * @param uri the relative URL of the page to be sent back to the client
     * @param bean a context object which can be accessed inside this page to extract various values and place them in the generated page
     * @param timeToLive time to live for the continuation created
     * @return the continuation
     */
    WebContinuation sendPageAndWait(in string uri, in Object bean, in long timeToLive);

    // Action Support

    /**
     * Call an action from JS
     */
    void act(in string type, in string source, in Object parameters);

    // InputModule Support

    /**
     * Obtain value from InputModule
     * @param type
     * @param attribute_
     */
    Object inputValue(in string type, in string attribute_);

    // OutputModule Support

    /**
     * Set an attribute (starts transaction, commit or rollback required!)
     * @param type (not sure)
     * @param attribute_ (not sure)
     * @param value (not sure)
     */
    void outputSet(in string type, in string attribute_, in Object value);

    /**
     * Makes attributes permanent (ends transaction)
     * @param type (not sure)
     */
    void outputCommit(in string type);

    /**
     * Deletes attributes (ends transaction)
     * @param type (not sure)
     */
    void outputRollback(in string type);

    /**
     * <p>
     * Entry point to a flow-based XMLForm application. Replaces the functionality
     * of XMLForm actions.
     * @param application Name of a JavaScript function that represents the page flow for a form
     * @param id form id
     * @param validator_ns XML namespace of validator
     * @param validator_doc validator document
     */
    void xmlForm(in string application,
                 in string id, in string validator_ns,
                 in string validator_doc);
};
