/**
 * <p>
 *   A Java &quot;native&quot; Iterator.
 * </p>
 * <p>
 *   Reference to a
 *   <a href="http://java.sun.com/products/jdk/1.2/docs/api/java/util/Iterator.html"
 *   >java.util.Iterator</a> object.
 * </p>
 *
 * <p>
 *   <dl>
 *     <dt><b>Copyright:</b></dt>
 *     <dd>
 *       Copyright &copy;
 *       <a href="http://java.sun.com/">Sun Microsystems, Inc.</a>
 *       All rights reserved.
 *     </dd>
 *   </dl>
 * </p>
 */
interface Iterator:JavaObject {
};
