/*****************************************************************************
 * Copyright (C) The Apache Software Foundation. All rights reserved.        *
 * ------------------------------------------------------------------------- *
 * This software is published under the terms of the Apache Software License *
 * version 1.1, a copy of which has been included  with this distribution in *
 * the LICENSE file.                                                         *
 *****************************************************************************/

package org.apache.cocoon.processors;

import org.apache.cocoon.*;

/**
 * The Processor interface.
 *
 * @author <a href="mailto:stefano@apache.org">Stefano Mazzocchi</a>
 * @version CVS $Revision: 1.1.2.1 $ $Date: 1999-12-11 23:28:52 $
 * @since 2.0
 */

public interface Processor extends EventListener {

	/**
	 * This method makes available to this class all the required information
	 * following an improved Servlet model that better separates contexts.
	 * 
	 * @param request The request wrapper
	 * @param request The response wrapper
	 * @param request The context wrapper
	 */    
    void set(Request request, Response response, Context context);
    
	/**
	 * Set the event listener receiving SAX events generated by this processor.
	 *
	 * @param handler The event listener receiving SAX events.
	 */
	void setEventListener(EventListener listener);
}