/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
/* ============================================================================ *
 *                   The Apache Software License, Version 1.1                   *
 * ============================================================================ *
 *                                                                              *
 * Copyright (C) 1999-2003 The Apache Software Foundation. All rights reserved. *
 *                                                                              *
 * Redistribution and use in source and binary forms, with or without modifica- *
 * tion, are permitted provided that the following conditions are met:          *
 *                                                                              *
 * 1. Redistributions of  source code must  retain the above copyright  notice, *
 *    this list of conditions and the following disclaimer.                     *
 *                                                                              *
 * 2. Redistributions in binary form must reproduce the above copyright notice, *
 *    this list of conditions and the following disclaimer in the documentation *
 *    and/or other materials provided with the distribution.                    *
 *                                                                              *
 * 3. The end-user documentation included with the redistribution, if any, must *
 *    include  the following  acknowledgment:  "This product includes  software *
 *    developed  by the  Apache Software Foundation  (http://www.apache.org/)." *
 *    Alternately, this  acknowledgment may  appear in the software itself,  if *
 *    and wherever such third-party acknowledgments normally appear.            *
 *                                                                              *
 * 4. The names "Apache Cocoon" and  "Apache Software Foundation" must  not  be *
 *    used to  endorse or promote  products derived from  this software without *
 *    prior written permission. For written permission, please contact          *
 *    apache@apache.org.                                                        *
 *                                                                              *
 * 5. Products  derived from this software may not  be called "Apache", nor may *
 *    "Apache" appear  in their name,  without prior written permission  of the *
 *    Apache Software Foundation.                                               *
 *                                                                              *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, *
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND *
 * FITNESS  FOR A PARTICULAR  PURPOSE ARE  DISCLAIMED.  IN NO  EVENT SHALL  THE *
 * APACHE SOFTWARE  FOUNDATION  OR ITS CONTRIBUTORS  BE LIABLE FOR  ANY DIRECT, *
 * INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL  DAMAGES (INCLU- *
 * DING, BUT NOT LIMITED TO, PROCUREMENT  OF SUBSTITUTE GOODS OR SERVICES; LOSS *
 * OF USE, DATA, OR  PROFITS; OR BUSINESS  INTERRUPTION)  HOWEVER CAUSED AND ON *
 * ANY  THEORY OF LIABILITY,  WHETHER  IN CONTRACT,  STRICT LIABILITY,  OR TORT *
 * (INCLUDING  NEGLIGENCE OR  OTHERWISE) ARISING IN  ANY WAY OUT OF THE  USE OF *
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.            *
 *                                                                              *
 * This software  consists of voluntary contributions made  by many individuals *
 * on  behalf of the Apache Software  Foundation.  For more  information on the *
 * Apache Software Foundation, please see <http://www.apache.org/>.             *
 *                                                                              *
 * ============================================================================ */

package org.apache.garbage.parser;

public interface ParserConstants {

  int EOF = 0;
  int XML_BaseChar = 1;
  int XML_Ideographic = 2;
  int XML_CombinChar = 3;
  int XML_Digit = 4;
  int XML_Extender = 5;
  int XML_Letter = 6;
  int XML_NameChar = 7;
  int PubIdChar = 8;
  int S = 9;
  int Name = 10;
  int T_CHARACTERS = 11;
  int T_DOCTYPE = 12;
  int T_DOCTYPE_END = 13;
  int T_DOCTYPE_NAME = 14;
  int T_DOCTYPE_SYSTEM = 15;
  int T_DOCTYPE_PUBLIC = 16;
  int T_DOCTYPE_S = 17;
  int T_DOCTYPE_QUOT = 18;
  int T_DOCTYPE_APOS = 19;
  int T_DOCTYPE_SYSTEM_DATA = 20;
  int T_DOCTYPE_PUBLIC_DATA = 21;
  int T_ELEMENT_OPEN = 22;
  int T_ELEMENT_CLOSE = 23;
  int T_ELEMENT_END = 24;
  int T_ELEMENT_SINGLE = 25;
  int T_ATTRIBUTE = 26;
  int T_ATTRIBUTE_EQUALS = 27;
  int T_ATTRIBUTE_QUOT = 28;
  int T_ATTRIBUTE_APOS = 29;
  int T_ATTRIBUTE_EXPR = 30;
  int T_ATTRIBUTE_EREF = 31;
  int T_ATTRIBUTE_DATA = 32;
  int T_ENTITYREF = 33;
  int T_ENTITYREF_END = 34;
  int T_ENTITYREF_NUM = 35;
  int T_ENTITYREF_HEX = 36;
  int T_ENTITYREF_NAME = 37;
  int T_COMMENT = 38;
  int T_COMMENT_END = 39;
  int T_COMMENT_DATA = 40;
  int T_CDATA = 41;
  int T_CDATA_END = 42;
  int T_CDATA_DATA = 43;
  int T_PROCINSTR = 44;
  int T_PROCINSTR_END = 45;
  int T_PROCINSTR_SEP = 46;
  int T_PROCINSTR_TARGET = 47;
  int T_PROCINSTR_DATA = 48;
  int T_EXPRESSION = 49;
  int T_EXPRESSION_END = 50;
  int T_EXPRESSION_DATA = 51;
  int T_TEMPLATE_IF = 52;
  int T_TEMPLATE_ELIF = 53;
  int T_TEMPLATE_ELSE = 54;
  int T_TEMPLATE_FOREACH = 55;
  int T_TEMPLATE_END = 56;
  int T_TEMPLATE_VARIABLE = 57;

  int DEFAULT = 0;
  int DOCTYPE = 1;
  int DOCTYPE_SYSTEM = 2;
  int DOCTYPE_PUBLIC = 3;
  int ELEMENT = 4;
  int ATTRIBUTE = 5;
  int ATTRIBUTE_DATA = 6;
  int ENTITYREF = 7;
  int COMMENT = 8;
  int CDATA = 9;
  int PROCINSTR = 10;
  int PROCINSTR_DATA = 11;
  int EXPRESSION = 12;

  String[] tokenImage = {
    "<EOF>",
    "<XML_BaseChar>",
    "<XML_Ideographic>",
    "<XML_CombinChar>",
    "<XML_Digit>",
    "<XML_Extender>",
    "<XML_Letter>",
    "<XML_NameChar>",
    "<PubIdChar>",
    "<S>",
    "<Name>",
    "<T_CHARACTERS>",
    "<T_DOCTYPE>",
    "<T_DOCTYPE_END>",
    "<T_DOCTYPE_NAME>",
    "<T_DOCTYPE_SYSTEM>",
    "<T_DOCTYPE_PUBLIC>",
    "<T_DOCTYPE_S>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<T_DOCTYPE_SYSTEM_DATA>",
    "<T_DOCTYPE_PUBLIC_DATA>",
    "<T_ELEMENT_OPEN>",
    "<T_ELEMENT_CLOSE>",
    "<T_ELEMENT_END>",
    "<T_ELEMENT_SINGLE>",
    "<T_ATTRIBUTE>",
    "<T_ATTRIBUTE_EQUALS>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"{\"",
    "\"&\"",
    "<T_ATTRIBUTE_DATA>",
    "\"&\"",
    "\";\"",
    "<T_ENTITYREF_NUM>",
    "<T_ENTITYREF_HEX>",
    "<T_ENTITYREF_NAME>",
    "\"<!--\"",
    "\"-->\"",
    "<T_COMMENT_DATA>",
    "\"<[CDATA[\"",
    "\"]]>\"",
    "<T_CDATA_DATA>",
    "\"<?\"",
    "\"?>\"",
    "<T_PROCINSTR_SEP>",
    "<T_PROCINSTR_TARGET>",
    "<T_PROCINSTR_DATA>",
    "\"#{\"",
    "\"}\"",
    "<T_EXPRESSION_DATA>",
    "<T_TEMPLATE_IF>",
    "<T_TEMPLATE_ELIF>",
    "\"#else\"",
    "<T_TEMPLATE_FOREACH>",
    "\"#end\"",
    "<T_TEMPLATE_VARIABLE>",
  };

}
