/* Generated by Together */

package org.apache.cocoon.components.saxconnector;

import org.apache.cocoon.xml.AbstractXMLPipe;
import org.apache.excalibur.pool.Poolable;
import org.apache.avalon.parameters.Parameters;

import org.apache.cocoon.ProcessingException;
import org.apache.cocoon.sitemap.Sitemap;

import org.xml.sax.SAXException;
import org.xml.sax.EntityResolver;

import java.util.Map;
import java.io.IOException;

/**
 * Null implementation of the SAXConnector. Simply sends events on to the next component in the pipeline.
 * @author <a href="prussell@apache.org">Paul Russell</a>
 * @version CVS $Revision: 1.1.2.5 $ $Date: 2001-04-24 20:18:25 $
 */
public class NullSAXConnector extends AbstractXMLPipe implements Poolable, SAXConnector {

    /** Setup this SAXConnector.
     */
    public void setup(EntityResolver resolver, Map objectModel, String src, Parameters params)
    throws ProcessingException, SAXException, IOException {
        // do nothing.
    }
}
