/* Generated by Together */

package org.apache.cocoon.components.saxconnector;

import org.xml.sax.helpers.XMLFilterImpl;
import org.apache.cocoon.xml.AbstractXMLPipe;
import org.apache.avalon.Poolable;

/**
 * Null implementation of the SAXConnector. Simply sends events on to the next component in the pipeline.
 * @author <a href="prussell@apache.org">Paul Russell</a> 
 * @version CVS $Revision: 1.1.2.1 $ $Date: 2001-03-03 15:56:38 $
 */
public class NullSAXConnector extends AbstractXMLPipe implements Poolable, SAXConnector {    
}
