/* Generated by Together */

package org.apache.cocoon.components.saxconnector;

import org.xml.sax.XMLFilter;
import org.apache.avalon.Component;
import org.apache.cocoon.xml.XMLPipe;

/**
 * Provides a connection between SAX components.
 * @author <a href="mailto:prussell@apache.org">Paul Russell</a> 
 * @version CVS $Revision: 1.1.2.1 $ $Date: 2001-03-03 15:56:36 $
 */
public interface SAXConnector extends XMLPipe, Component {
}
